version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

  redis:
    image: "redis:latest"
    container_name: redis
    ports:
      - "6379:6379"

  celery:
    build:
      context: .  # Path to the directory containing your Dockerfile
      dockerfile: Dockerfile.celery  # Specify the new Dockerfile name
    volumes:
      - .:/app  # Optional: If you need the project files
    depends_on:
      - redis
      - kafka
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
