spring:
  datasource:
    url: jdbc:mysql://localhost:3306/my-daily-track
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always
  kafka:
    consumer:
      topic:
        goal-completed: completed-goals-topic
        history: history-topic
      group-id: history-service-group
    bootstrap-servers: localhost:9092
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: 'true'
    hibernate:
      ddl-auto: none
    show-sql: 'true'
logging:
  level:
    org:
      hibernate:
        orm:
          jdbc:
            bind: TRACE

