spring:
  datasource:
    url: jdbc:mysql://localhost:3306/e-commerce
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: 'true'
    hibernate:
      ddl-auto: none
    show-sql: 'true'
logging:
  level:
    org:
      hibernate:
        orm:
          jdbc:
            bind: TRACE
