spring:
  datasource:
    url: jdbc:mysql://localhost:3306/my-daily-track
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always
  kafka:
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      auto-offset-reset: earliest
      group-id: group_id
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            value:
              default:
                type: com.example.Message
    bootstrap-servers: localhost:9092
    admin:
      topic:
        replication-factor: '1'
        partitions: '3'
        name: my_topic
      properties:
        auto:
          create:
            topics:
              enable: 'false'
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: 'true'
    hibernate:
      ddl-auto: none
    show-sql: 'true'
logging:
  level:
    org:
      hibernate:
        orm:
          jdbc:
            bind: TRACE

