spring:
  datasource:
    url: jdbc:mysql://localhost:3306/my-daily-track
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always
  kafka:
    consumer:
      auto-offset-reset: earliest
      group-id: history-service-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    topic:
      goal-completed: completed-goals-topic
    bootstrap-servers: localhost:9092
    admin:
      topic:
        replication-factor: '1' # copies of a topic's partitions across brokers
        partitions: '3' # my_topic will have 3 partitions. If you are using multiple consumers in your history-service-group, Kafka will distribute the load across these partitions
        name: my_topic
      properties:
        auto:
          create:
            topics:
              enable: 'false'
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: 'true'
    hibernate:
      ddl-auto: none
    show-sql: 'true'
logging:
  level:
    org:
      hibernate:
        orm:
          jdbc:
            bind: TRACE

